name: Continuous Persistent VPS

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 350 # Just under 6 hours

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Download last backup
      - name: Download VPS backup (if any)
        uses: actions/download-artifact@v4
        with:
          name: vps-backup
          path: ./backup
        continue-on-error: true

      # 3. Restore full system from backup
      - name: Restore VPS from backup
        run: |
          if [ -f ./backup/backup.tar.gz.partaa ]; then
            cat ./backup/backup.tar.gz.parta* > backup.tar.gz
            sudo tar --numeric-owner -xpf backup.tar.gz -C /
            echo "✅ VPS restored from backup"
            rm -f backup.tar.gz ./backup/backup.tar.gz.parta*
          else
            echo "ℹ️ No previous backup found, starting fresh"
          fi

      # 4. Install prerequisites
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch

      # 5. Install Tailscale
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      # 6. Start Tailscale with fixed hostname
      - name: Start Tailscale
        run: |
          sudo tailscaled &
          sleep 8
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname=Nubilux-1 || echo "Tailscale already up"

      # 7. Restart Wings (if exists)
      - name: Restart Wings service
        run: |
          if sudo systemctl list-units --type=service | grep -q wings.service; then
            sudo systemctl restart wings.service
            echo "✅ Wings restarted"
          else
            echo "ℹ️ Wings not installed yet"
          fi

      # 8. Start tmate for remote access
      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3

      # 9. Keep VPS alive for 6 hours
      - name: Sleep to keep VPS alive
        run: sleep 21600

      # 10. Backup VPS before shutdown
      - name: Backup VPS
        run: |
          sudo tar --exclude=/proc --exclude=/sys --exclude=/dev \
                   --exclude=/tmp --exclude=/run --exclude=/mnt \
                   --exclude=/media --exclude=/lost+found \
                   --numeric-owner -cpzf backup.tar.gz /
          split -b 2000M backup.tar.gz "backup.tar.gz.part"
          rm -f backup.tar.gz

      # 11. Upload backup artifact
      - name: Upload VPS backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: vps-backup
          path: backup.tar.gz.part*
